//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace queryTest.webapi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webapi.IAPIService")]
    public interface IAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/getStock", ReplyAction="http://tempuri.org/IAPIService/getStockResponse")]
        string getStock(string token, int t_StartTime, int t_EndTime, int PageSize, int PageIndex, string CPXH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/getStock", ReplyAction="http://tempuri.org/IAPIService/getStockResponse")]
        System.Threading.Tasks.Task<string> getStockAsync(string token, int t_StartTime, int t_EndTime, int PageSize, int PageIndex, string CPXH);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAPIServiceChannel : queryTest.webapi.IAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIServiceClient : System.ServiceModel.ClientBase<queryTest.webapi.IAPIService>, queryTest.webapi.IAPIService {
        
        public APIServiceClient() {
        }
        
        public APIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getStock(string token, int t_StartTime, int t_EndTime, int PageSize, int PageIndex, string CPXH) {
            return base.Channel.getStock(token, t_StartTime, t_EndTime, PageSize, PageIndex, CPXH);
        }
        
        public System.Threading.Tasks.Task<string> getStockAsync(string token, int t_StartTime, int t_EndTime, int PageSize, int PageIndex, string CPXH) {
            return base.Channel.getStockAsync(token, t_StartTime, t_EndTime, PageSize, PageIndex, CPXH);
        }
    }
}
