//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hn.TimerService.APIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIService.IAPIService")]
    public interface IAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/WmStock", ReplyAction="http://tempuri.org/IAPIService/WmStockResponse")]
        System.Data.DataTable WmStock(out int pagecount, string productnumber, string productname, string stockname, string brandname, string batchno, string wdr, string mode, string colorno, int pagesize, int page, bool isfactory, bool istrust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/ICSEOUTBILLSync", ReplyAction="http://tempuri.org/IAPIService/ICSEOUTBILLSyncResponse")]
        string ICSEOUTBILLSync(hn.DataAccess.Model.V_ICSEOUTBILLMODEL[] icseout, hn.DataAccess.Model.V_ICSEOUTBILLENTRYMODEL[] icseoutentry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetICSEOUTUpdateData", ReplyAction="http://tempuri.org/IAPIService/GetICSEOUTUpdateDataResponse")]
        System.Data.DataTable GetICSEOUTUpdateData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateCSEOUTSyncStatus", ReplyAction="http://tempuri.org/IAPIService/UpdateCSEOUTSyncStatusResponse")]
        string UpdateCSEOUTSyncStatus(int id, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetICSEOUTUpdateData2", ReplyAction="http://tempuri.org/IAPIService/GetICSEOUTUpdateData2Response")]
        System.Data.DataTable GetICSEOUTUpdateData2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateCSEOUTSyncStatus2", ReplyAction="http://tempuri.org/IAPIService/UpdateCSEOUTSyncStatus2Response")]
        string UpdateCSEOUTSyncStatus2(int id, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetSTOCKUpdateData", ReplyAction="http://tempuri.org/IAPIService/GetSTOCKUpdateDataResponse")]
        System.Data.DataTable GetSTOCKUpdateData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetTMP_STOCKBill", ReplyAction="http://tempuri.org/IAPIService/GetTMP_STOCKBillResponse")]
        System.Data.DataTable GetTMP_STOCKBill();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateTMP_STOCKBillStatus", ReplyAction="http://tempuri.org/IAPIService/UpdateTMP_STOCKBillStatusResponse")]
        string UpdateTMP_STOCKBillStatus(int id, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetFinfo_RE_id0", ReplyAction="http://tempuri.org/IAPIService/GetFinfo_RE_id0Response")]
        System.Data.DataTable GetFinfo_RE_id0();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateFinfo_RE_id", ReplyAction="http://tempuri.org/IAPIService/UpdateFinfo_RE_idResponse")]
        string UpdateFinfo_RE_id(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/InventorySync", ReplyAction="http://tempuri.org/IAPIService/InventorySyncResponse")]
        string InventorySync(hn.DataAccess.Model.SALES_ORDER_DATAMODEL[] salesOrderDatas, hn.DataAccess.Model.SALESOUT_DATAMODEL[] salesoutDatas, hn.DataAccess.Model.TP_INVENTORYMODEL[] inventorys);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAPIServiceChannel : hn.TimerService.APIService.IAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIServiceClient : System.ServiceModel.ClientBase<hn.TimerService.APIService.IAPIService>, hn.TimerService.APIService.IAPIService {
        
        public APIServiceClient() {
        }
        
        public APIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable WmStock(out int pagecount, string productnumber, string productname, string stockname, string brandname, string batchno, string wdr, string mode, string colorno, int pagesize, int page, bool isfactory, bool istrust) {
            return base.Channel.WmStock(out pagecount, productnumber, productname, stockname, brandname, batchno, wdr, mode, colorno, pagesize, page, isfactory, istrust);
        }
        
        public string ICSEOUTBILLSync(hn.DataAccess.Model.V_ICSEOUTBILLMODEL[] icseout, hn.DataAccess.Model.V_ICSEOUTBILLENTRYMODEL[] icseoutentry) {
            return base.Channel.ICSEOUTBILLSync(icseout, icseoutentry);
        }
        
        public System.Data.DataTable GetICSEOUTUpdateData() {
            return base.Channel.GetICSEOUTUpdateData();
        }
        
        public string UpdateCSEOUTSyncStatus(int id, int status) {
            return base.Channel.UpdateCSEOUTSyncStatus(id, status);
        }
        
        public System.Data.DataTable GetICSEOUTUpdateData2() {
            return base.Channel.GetICSEOUTUpdateData2();
        }
        
        public string UpdateCSEOUTSyncStatus2(int id, int status) {
            return base.Channel.UpdateCSEOUTSyncStatus2(id, status);
        }
        
        public System.Data.DataTable GetSTOCKUpdateData() {
            return base.Channel.GetSTOCKUpdateData();
        }
        
        public System.Data.DataTable GetTMP_STOCKBill() {
            return base.Channel.GetTMP_STOCKBill();
        }
        
        public string UpdateTMP_STOCKBillStatus(int id, int status) {
            return base.Channel.UpdateTMP_STOCKBillStatus(id, status);
        }
        
        public System.Data.DataTable GetFinfo_RE_id0() {
            return base.Channel.GetFinfo_RE_id0();
        }
        
        public string UpdateFinfo_RE_id(int id) {
            return base.Channel.UpdateFinfo_RE_id(id);
        }
        
        public string InventorySync(hn.DataAccess.Model.SALES_ORDER_DATAMODEL[] salesOrderDatas, hn.DataAccess.Model.SALESOUT_DATAMODEL[] salesoutDatas, hn.DataAccess.Model.TP_INVENTORYMODEL[] inventorys) {
            return base.Channel.InventorySync(salesOrderDatas, salesoutDatas, inventorys);
        }
    }
}
