//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hn.Client.ApiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApiService.IAPIService")]
    public interface IAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UnAuditSave_ICPO", ReplyAction="http://tempuri.org/IAPIService/UnAuditSave_ICPOResponse")]
        bool UnAuditSave_ICPO(hn.DataAccess.Model.ICPOBILLENTRYMODEL[] data, hn.Core.Model.User loginUser, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Remote_InsertICPOEntry", ReplyAction="http://tempuri.org/IAPIService/Remote_InsertICPOEntryResponse")]
        string Remote_InsertICPOEntry(MApiModel.api3.Rootobject getapi3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Remote_GetICPOEntry", ReplyAction="http://tempuri.org/IAPIService/Remote_GetICPOEntryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hn.DataAccess.Model.V_ICPOBILLMODEL))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hn.DataAccess.Model.V_ICPOBILLENTRYMODEL))]
        void Remote_GetICPOEntry(string strFID, string strEntryID, ref hn.DataAccess.Model.ICPOBILLMODEL billModel, ref hn.DataAccess.Model.ICPOBILLENTRYMODEL entryModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Remote_GetICPO_BOEntry", ReplyAction="http://tempuri.org/IAPIService/Remote_GetICPO_BOEntryResponse")]
        hn.DataAccess.Model.ICPO_BOLentryModel[] Remote_GetICPO_BOEntry(string fbillno, string entryid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Remote_SetICPO_BOEntryStatus", ReplyAction="http://tempuri.org/IAPIService/Remote_SetICPO_BOEntryStatusResponse")]
        int Remote_SetICPO_BOEntryStatus(string fbillno, string entryid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Save_ICPREntry_List", ReplyAction="http://tempuri.org/IAPIService/Save_ICPREntry_ListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hn.DataAccess.Model.V_ICPRBILLENTRYMODEL))]
        string Save_ICPREntry_List(hn.DataAccess.Model.ICPRBILLENTRYMODEL tModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Update_FSYNStatus", ReplyAction="http://tempuri.org/IAPIService/Update_FSYNStatusResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hn.DataAccess.Model.V_ICPOBILLMODEL))]
        int Update_FSYNStatus(hn.DataAccess.Model.ICPOBILLMODEL billMode, int iStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Update_FSYN_Remote_Status", ReplyAction="http://tempuri.org/IAPIService/Update_FSYN_Remote_StatusResponse")]
        int Update_FSYN_Remote_Status(string billMode, int iStatus, string cjbh, System.Collections.Generic.Dictionary<int, string> dic_entry_thdbmdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Forder_confirm", ReplyAction="http://tempuri.org/IAPIService/Forder_confirmResponse")]
        hn.DataAccess.DataResult Forder_confirm(hn.DataAccess.bll.Forder_confirm_Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Forder_delivery", ReplyAction="http://tempuri.org/IAPIService/Forder_deliveryResponse")]
        hn.DataAccess.DataResult Forder_delivery(hn.DataAccess.bll.Forder_delivery_Input[] input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Sync_Today_THD", ReplyAction="http://tempuri.org/IAPIService/Sync_Today_THDResponse")]
        bool Sync_Today_THD(string rq1, string rq2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Login", ReplyAction="http://tempuri.org/IAPIService/LoginResponse")]
        hn.Core.Model.User Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/ModifyPassword", ReplyAction="http://tempuri.org/IAPIService/ModifyPasswordResponse")]
        string ModifyPassword(string id, string oldpwd, string newpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetDics", ReplyAction="http://tempuri.org/IAPIService/GetDicsResponse")]
        hn.DataAccess.Model.SYS_SUBDICSMODEL[] GetDics(string categorycode, string keyword, bool all);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Remote_Get24", ReplyAction="http://tempuri.org/IAPIService/Remote_Get24Response")]
        MApiModel.recApi24.Rootobject Remote_Get24(MApiModel.api24.Rootobject getapi24);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetDics_Area", ReplyAction="http://tempuri.org/IAPIService/GetDics_AreaResponse")]
        hn.DataAccess.Model.SYS_SUBDICSMODEL[] GetDics_Area(string categorycode, string keyword, bool all);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/getTHD", ReplyAction="http://tempuri.org/IAPIService/getTHDResponse")]
        hn.DataAccess.Model.v_thdModel getTHD(string thdbm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/ZFICPOBILL", ReplyAction="http://tempuri.org/IAPIService/ZFICPOBILLResponse")]
        string ZFICPOBILL(string fEntryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/ZFICPRBILLEntry", ReplyAction="http://tempuri.org/IAPIService/ZFICPRBILLEntryResponse")]
        string ZFICPRBILLEntry(string fEntryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/getICPOBillCLientID", ReplyAction="http://tempuri.org/IAPIService/getICPOBillCLientIDResponse")]
        hn.DataAccess.Model.V_ICPOBILLMODEL getICPOBillCLientID(string thdbm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/getLeftNum_THD", ReplyAction="http://tempuri.org/IAPIService/getLeftNum_THDResponse")]
        decimal getLeftNum_THD(string thdbm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPremiseList", ReplyAction="http://tempuri.org/IAPIService/GetPremiseListResponse")]
        hn.DataAccess.model.V_PREMISEModel[] GetPremiseList(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetBrandList", ReplyAction="http://tempuri.org/IAPIService/GetBrandListResponse")]
        hn.DataAccess.Model.TB_BrandModel[] GetBrandList(hn.Core.Model.User loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetClientAccountList", ReplyAction="http://tempuri.org/IAPIService/GetClientAccountListResponse")]
        hn.DataAccess.Model.V_CLIENTACCOUNTModel[] GetClientAccountList(string brandid, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetExpressCompanyList", ReplyAction="http://tempuri.org/IAPIService/GetExpressCompanyListResponse")]
        hn.DataAccess.Model.TB_EXPRESSCOMPANYModel[] GetExpressCompanyList(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetProductList", ReplyAction="http://tempuri.org/IAPIService/GetProductListResponse")]
        hn.DataAccess.model.ProductViewModel[] GetProductList(hn.Core.Model.User loginUser, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetSrcList", ReplyAction="http://tempuri.org/IAPIService/GetSrcListResponse")]
        hn.DataAccess.Model.SRCModel[] GetSrcList(string productid, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetProvince", ReplyAction="http://tempuri.org/IAPIService/GetProvinceResponse")]
        hn.DataAccess.model.TB_EBPLModel[] GetProvince();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetCity", ReplyAction="http://tempuri.org/IAPIService/GetCityResponse")]
        hn.DataAccess.model.TB_EBPLModel[] GetCity(string provinceid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetDistrict", ReplyAction="http://tempuri.org/IAPIService/GetDistrictResponse")]
        hn.DataAccess.model.TB_EBPLModel[] GetDistrict(string cityid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/getProductView", ReplyAction="http://tempuri.org/IAPIService/getProductViewResponse")]
        hn.DataAccess.model.ProductViewModel getProductView(string fid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetSingleDics", ReplyAction="http://tempuri.org/IAPIService/GetSingleDicsResponse")]
        hn.DataAccess.Model.SYS_SUBDICSMODEL GetSingleDics(string fid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetDeliverBaseList", ReplyAction="http://tempuri.org/IAPIService/GetDeliverBaseListResponse")]
        hn.DataAccess.model.TB_DELIVER_BASEModel[] GetDeliverBaseList(string brandid, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetClientAccountSingle", ReplyAction="http://tempuri.org/IAPIService/GetClientAccountSingleResponse")]
        hn.DataAccess.Model.V_CLIENTACCOUNTModel GetClientAccountSingle(string clientid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetClientByAccount", ReplyAction="http://tempuri.org/IAPIService/GetClientByAccountResponse")]
        hn.DataAccess.Model.V_CLIENTACCOUNTModel GetClientByAccount(string faccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPurchasePlanList", ReplyAction="http://tempuri.org/IAPIService/GetPurchasePlanListResponse")]
        hn.DataAccess.Model.V_ICPRBILLMODEL[] GetPurchasePlanList(hn.Core.Model.User loginUser, string classarea2name, string brand, int status, string premiseid, string billno, string startdate, string enddate, bool searchclose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPurchasePlanImport", ReplyAction="http://tempuri.org/IAPIService/GetPurchasePlanImportResponse")]
        hn.DataAccess.Model.V_ICPRBILLMODEL[] GetPurchasePlanImport(hn.Core.Model.User loginUser, string strQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPurchasePlanImport2", ReplyAction="http://tempuri.org/IAPIService/GetPurchasePlanImport2Response")]
        hn.DataAccess.Model.V_ICPRBILLMODEL[] GetPurchasePlanImport2(hn.Core.Model.User loginUser, string strQuery, string brandid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPurchasePlanImport3", ReplyAction="http://tempuri.org/IAPIService/GetPurchasePlanImport3Response")]
        hn.DataAccess.Model.V_ICPRBILLMODEL[] GetPurchasePlanImport3(hn.Core.Model.User loginUser, hn.Common.Cls_query.P_QueryOrder pquery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPurchasePlanModel", ReplyAction="http://tempuri.org/IAPIService/GetPurchasePlanModelResponse")]
        hn.DataAccess.Model.V_ICPRBILLMODEL GetPurchasePlanModel(string icprbillid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetV_ICPRBILLENTRYMODEL", ReplyAction="http://tempuri.org/IAPIService/GetV_ICPRBILLENTRYMODELResponse")]
        hn.DataAccess.Model.V_ICPRBILLENTRYMODEL GetV_ICPRBILLENTRYMODEL(string FID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/V_ICPRBILLENTRYMODEL_List", ReplyAction="http://tempuri.org/IAPIService/V_ICPRBILLENTRYMODEL_ListResponse")]
        hn.DataAccess.Model.V_ICPRBILLENTRYMODEL[] V_ICPRBILLENTRYMODEL_List(string fpremisename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPurchasePlanEntryList", ReplyAction="http://tempuri.org/IAPIService/GetPurchasePlanEntryListResponse")]
        hn.DataAccess.Model.V_ICPRBILLENTRYMODEL[] GetPurchasePlanEntryList(string icprbillid, string statu, bool bICPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/Delete_ICPO", ReplyAction="http://tempuri.org/IAPIService/Delete_ICPOResponse")]
        bool Delete_ICPO(string fid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPurchasePlanEntryByDeliveryList", ReplyAction="http://tempuri.org/IAPIService/GetPurchasePlanEntryByDeliveryListResponse")]
        hn.DataAccess.Model.V_ICPRBILLENTRYMODEL[] GetPurchasePlanEntryByDeliveryList(hn.Core.Model.User loginUser, string productinfo, string classarea2name, string premiseid, string brand, string deliveryaddr, string typename, string billno, int status, bool bHaveSL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/ConfirmSave", ReplyAction="http://tempuri.org/IAPIService/ConfirmSaveResponse")]
        bool ConfirmSave(string action, hn.DataAccess.Model.ICPRBILLENTRYMODEL[] data, hn.Core.Model.User loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/CloseSave", ReplyAction="http://tempuri.org/IAPIService/CloseSaveResponse")]
        bool CloseSave(hn.DataAccess.Model.ICPRBILLENTRYMODEL[] data, hn.Core.Model.User loginUser, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetStockList", ReplyAction="http://tempuri.org/IAPIService/GetStockListResponse")]
        System.Data.DataTable GetStockList(string productname, string stockname, string productnumber, string wdr, string batchno, string brand, string mode, string colorno, bool isfactory, bool istrust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetStockListMN", ReplyAction="http://tempuri.org/IAPIService/GetStockListMNResponse")]
        MApiModel.recApi2.Rootobject GetStockListMN(MApiModel.api2.Rootobject getapi2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetStockListMN_2", ReplyAction="http://tempuri.org/IAPIService/GetStockListMN_2Response")]
        MApiModel.recApi2.Rootobject GetStockListMN_2(MApiModel.api2.Rootobject getapi2, int comid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetAttachmentList", ReplyAction="http://tempuri.org/IAPIService/GetAttachmentListResponse")]
        hn.DataAccess.Model.TB_ATTACHMENTModel[] GetAttachmentList(string icprbillid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateICPRBILL", ReplyAction="http://tempuri.org/IAPIService/UpdateICPRBILLResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hn.DataAccess.Model.V_ICPRBILLMODEL))]
        int UpdateICPRBILL(hn.DataAccess.Model.ICPRBILLMODEL model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/RefrshPriceNumberList", ReplyAction="http://tempuri.org/IAPIService/RefrshPriceNumberListResponse")]
        hn.DataAccess.Model.V_ICPRBILLENTRYMODEL[] RefrshPriceNumberList(string icprbillid, string[] entryids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPriceNumberListByItemID", ReplyAction="http://tempuri.org/IAPIService/GetPriceNumberListByItemIDResponse")]
        hn.DataAccess.model.TB_PRICEPOLICYModel[] GetPriceNumberListByItemID(string itemid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPriceNumberListByBrandID", ReplyAction="http://tempuri.org/IAPIService/GetPriceNumberListByBrandIDResponse")]
        hn.DataAccess.model.TB_PRICEPOLICYModel[] GetPriceNumberListByBrandID(string itemid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateConfirmTime", ReplyAction="http://tempuri.org/IAPIService/UpdateConfirmTimeResponse")]
        void UpdateConfirmTime(string FPlanId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/getTHDList", ReplyAction="http://tempuri.org/IAPIService/getTHDListResponse")]
        hn.DataAccess.Model.v_thdModel[] getTHDList(string[] thdbmList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetNewBillNo", ReplyAction="http://tempuri.org/IAPIService/GetNewBillNoResponse")]
        string GetNewBillNo(string billtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/DeleteGroupBill", ReplyAction="http://tempuri.org/IAPIService/DeleteGroupBillResponse")]
        bool DeleteGroupBill(string groupno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/DeliveryBillSave", ReplyAction="http://tempuri.org/IAPIService/DeliveryBillSaveResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hn.DataAccess.Model.V_ICSEOUTBILLMODEL))]
        bool DeliveryBillSave(hn.DataAccess.Model.ICSEOUTBILLMODEL model, hn.DataAccess.Model.ICSEOUTBILLENTRYMODEL[] entrys, bool delivery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateIdentification", ReplyAction="http://tempuri.org/IAPIService/UpdateIdentificationResponse")]
        bool UpdateIdentification(string ids, string centent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetDeliveryList", ReplyAction="http://tempuri.org/IAPIService/GetDeliveryListResponse")]
        hn.DataAccess.Model.V_ICSEOUTBILLMODEL[] GetDeliveryList(
                    hn.Core.Model.User loginUser, 
                    string brand, 
                    string classarea2name, 
                    string premiseid, 
                    int status, 
                    string car, 
                    string stock, 
                    string account, 
                    string expresscompany, 
                    string factotryno, 
                    string billno, 
                    string groupno, 
                    string projectname, 
                    string startdate, 
                    string enddate, 
                    bool searchclose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetDeliveryEntryList", ReplyAction="http://tempuri.org/IAPIService/GetDeliveryEntryListResponse")]
        hn.DataAccess.Model.V_ICSEOUTBILLENTRYMODEL[] GetDeliveryEntryList(string billid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/DeleteDeliveryByIDs", ReplyAction="http://tempuri.org/IAPIService/DeleteDeliveryByIDsResponse")]
        int DeleteDeliveryByIDs(string ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/AuditDeliveryByIDs", ReplyAction="http://tempuri.org/IAPIService/AuditDeliveryByIDsResponse")]
        int AuditDeliveryByIDs(string ids, int status, hn.Core.Model.User loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/AuditAntiDeliveryByIDs", ReplyAction="http://tempuri.org/IAPIService/AuditAntiDeliveryByIDsResponse")]
        int AuditAntiDeliveryByIDs(string ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/SyncDeliveryByIDs", ReplyAction="http://tempuri.org/IAPIService/SyncDeliveryByIDsResponse")]
        string SyncDeliveryByIDs(string ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/SyncDeliveryByIDsMN", ReplyAction="http://tempuri.org/IAPIService/SyncDeliveryByIDsMNResponse")]
        string SyncDeliveryByIDsMN(string strJson, string fid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/SynDeliveryNot", ReplyAction="http://tempuri.org/IAPIService/SynDeliveryNotResponse")]
        string SynDeliveryNot(string fid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetDeliveryEntryByGroupNo", ReplyAction="http://tempuri.org/IAPIService/GetDeliveryEntryByGroupNoResponse")]
        hn.DataAccess.Model.V_ICSEOUTBILLENTRYMODEL[] GetDeliveryEntryByGroupNo(string groupno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetDeliveryByGroupNo", ReplyAction="http://tempuri.org/IAPIService/GetDeliveryByGroupNoResponse")]
        hn.DataAccess.Model.V_ICSEOUTBILLMODEL[] GetDeliveryByGroupNo(string groupno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetSrcModelByItemID", ReplyAction="http://tempuri.org/IAPIService/GetSrcModelByItemIDResponse")]
        hn.DataAccess.Model.SRCModel GetSrcModelByItemID(string itemid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateGetDeliveryEntryData", ReplyAction="http://tempuri.org/IAPIService/UpdateGetDeliveryEntryDataResponse")]
        bool UpdateGetDeliveryEntryData(string id, decimal commitqty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetDismantlingNo", ReplyAction="http://tempuri.org/IAPIService/GetDismantlingNoResponse")]
        string GetDismantlingNo(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateDeliveryGroupStatus", ReplyAction="http://tempuri.org/IAPIService/UpdateDeliveryGroupStatusResponse")]
        string UpdateDeliveryGroupStatus(string ids, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/ContractCar", ReplyAction="http://tempuri.org/IAPIService/ContractCarResponse")]
        string ContractCar(string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/SaveICPOBILL", ReplyAction="http://tempuri.org/IAPIService/SaveICPOBILLResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hn.DataAccess.Model.V_ICPOBILLMODEL))]
        string SaveICPOBILL(hn.DataAccess.Model.ICPOBILLMODEL ICPOBILL, hn.DataAccess.Model.ICPOBILLENTRYMODEL[] ICPOBILLENTRYList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetOrderList", ReplyAction="http://tempuri.org/IAPIService/GetOrderListResponse")]
        hn.DataAccess.Model.V_ICPOBILLMODEL[] GetOrderList(hn.Core.Model.User loginUser, string classarea2name, string brand, int status, string premiseid, string billno, string startdate, string enddate, bool searchclose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetOrderEntryList", ReplyAction="http://tempuri.org/IAPIService/GetOrderEntryListResponse")]
        hn.DataAccess.Model.V_ICPOBILLENTRYMODEL[] GetOrderEntryList(string icprbillid, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetSingleOrder", ReplyAction="http://tempuri.org/IAPIService/GetSingleOrderResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hn.DataAccess.Model.V_ICPOBILLMODEL))]
        hn.DataAccess.Model.ICPOBILLMODEL GetSingleOrder(string icprbillid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GeICPO_BOLList", ReplyAction="http://tempuri.org/IAPIService/GeICPO_BOLListResponse")]
        hn.DataAccess.Model.ICPO_BOLentryModel[] GeICPO_BOLList(hn.Core.Model.User loginUser, string FPObillno, string Ficbolno, int FSYNCSTATUS, string FACCOUNT, string FITEMID, string startdate, string enddate, bool searchclose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetStartDate_syn", ReplyAction="http://tempuri.org/IAPIService/GetStartDate_synResponse")]
        string GetStartDate_syn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetStartDate_syn_cc", ReplyAction="http://tempuri.org/IAPIService/GetStartDate_syn_ccResponse")]
        string GetStartDate_syn_cc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetJYDW", ReplyAction="http://tempuri.org/IAPIService/GetJYDWResponse")]
        hn.DataAccess.model.TB_PREMISEModel[] GetJYDW(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/getSrc", ReplyAction="http://tempuri.org/IAPIService/getSrcResponse")]
        hn.DataAccess.Model.SRCModel getSrc(string pz, string gg, string xh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetArea2", ReplyAction="http://tempuri.org/IAPIService/GetArea2Response")]
        hn.DataAccess.Model.SYS_SUBDICSMODEL GetArea2(string fid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GeICPO_BOLListMN_syn", ReplyAction="http://tempuri.org/IAPIService/GeICPO_BOLListMN_synResponse")]
        string GeICPO_BOLListMN_syn(System.DateTime starttime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetLocalSum", ReplyAction="http://tempuri.org/IAPIService/GetLocalSumResponse")]
        int GetLocalSum(string autoid, string icseoutbillentryid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GeICPO_BOLListMN_syn_cc", ReplyAction="http://tempuri.org/IAPIService/GeICPO_BOLListMN_syn_ccResponse")]
        string GeICPO_BOLListMN_syn_cc(System.DateTime starttime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetCCD", ReplyAction="http://tempuri.org/IAPIService/GetCCDResponse")]
        string GetCCD(System.DateTime starttime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/v_thdModel_List", ReplyAction="http://tempuri.org/IAPIService/v_thdModel_ListResponse")]
        hn.DataAccess.model.v_thd[] v_thdModel_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/v_thdModelName_List", ReplyAction="http://tempuri.org/IAPIService/v_thdModelName_ListResponse")]
        string[] v_thdModelName_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GeICPO_BOLListMN_db", ReplyAction="http://tempuri.org/IAPIService/GeICPO_BOLListMN_dbResponse")]
        hn.DataAccess.Model.v_thdModel[] GeICPO_BOLListMN_db(MApiModel.api8.Rootobject getapi8, string cpxh, string cpgg, string jhdh, string thd, string area2, int bNotArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/ConfirmSave_ICPO", ReplyAction="http://tempuri.org/IAPIService/ConfirmSave_ICPOResponse")]
        bool ConfirmSave_ICPO(string action, hn.DataAccess.Model.ICPOBILLENTRYMODEL[] data, hn.Core.Model.User loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/CloseSave_ICPO", ReplyAction="http://tempuri.org/IAPIService/CloseSave_ICPOResponse")]
        bool CloseSave_ICPO(hn.DataAccess.Model.ICPOBILLENTRYMODEL[] data, hn.Core.Model.User loginUser, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/AuditSave_ICPO", ReplyAction="http://tempuri.org/IAPIService/AuditSave_ICPOResponse")]
        bool AuditSave_ICPO(hn.DataAccess.Model.ICPOBILLENTRYMODEL[] data, hn.Core.Model.User loginUser, string content);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAPIServiceChannel : hn.Client.ApiService.IAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIServiceClient : System.ServiceModel.ClientBase<hn.Client.ApiService.IAPIService>, hn.Client.ApiService.IAPIService {
        
        public APIServiceClient() {
        }
        
        public APIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UnAuditSave_ICPO(hn.DataAccess.Model.ICPOBILLENTRYMODEL[] data, hn.Core.Model.User loginUser, string content) {
            return base.Channel.UnAuditSave_ICPO(data, loginUser, content);
        }
        
        public string Remote_InsertICPOEntry(MApiModel.api3.Rootobject getapi3) {
            return base.Channel.Remote_InsertICPOEntry(getapi3);
        }
        
        public void Remote_GetICPOEntry(string strFID, string strEntryID, ref hn.DataAccess.Model.ICPOBILLMODEL billModel, ref hn.DataAccess.Model.ICPOBILLENTRYMODEL entryModel) {
            base.Channel.Remote_GetICPOEntry(strFID, strEntryID, ref billModel, ref entryModel);
        }
        
        public hn.DataAccess.Model.ICPO_BOLentryModel[] Remote_GetICPO_BOEntry(string fbillno, string entryid) {
            return base.Channel.Remote_GetICPO_BOEntry(fbillno, entryid);
        }
        
        public int Remote_SetICPO_BOEntryStatus(string fbillno, string entryid) {
            return base.Channel.Remote_SetICPO_BOEntryStatus(fbillno, entryid);
        }
        
        public string Save_ICPREntry_List(hn.DataAccess.Model.ICPRBILLENTRYMODEL tModel) {
            return base.Channel.Save_ICPREntry_List(tModel);
        }
        
        public int Update_FSYNStatus(hn.DataAccess.Model.ICPOBILLMODEL billMode, int iStatus) {
            return base.Channel.Update_FSYNStatus(billMode, iStatus);
        }
        
        public int Update_FSYN_Remote_Status(string billMode, int iStatus, string cjbh, System.Collections.Generic.Dictionary<int, string> dic_entry_thdbmdetail) {
            return base.Channel.Update_FSYN_Remote_Status(billMode, iStatus, cjbh, dic_entry_thdbmdetail);
        }
        
        public hn.DataAccess.DataResult Forder_confirm(hn.DataAccess.bll.Forder_confirm_Input input) {
            return base.Channel.Forder_confirm(input);
        }
        
        public hn.DataAccess.DataResult Forder_delivery(hn.DataAccess.bll.Forder_delivery_Input[] input) {
            return base.Channel.Forder_delivery(input);
        }
        
        public bool Sync_Today_THD(string rq1, string rq2) {
            return base.Channel.Sync_Today_THD(rq1, rq2);
        }
        
        public hn.Core.Model.User Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public string ModifyPassword(string id, string oldpwd, string newpwd) {
            return base.Channel.ModifyPassword(id, oldpwd, newpwd);
        }
        
        public hn.DataAccess.Model.SYS_SUBDICSMODEL[] GetDics(string categorycode, string keyword, bool all) {
            return base.Channel.GetDics(categorycode, keyword, all);
        }
        
        public MApiModel.recApi24.Rootobject Remote_Get24(MApiModel.api24.Rootobject getapi24) {
            return base.Channel.Remote_Get24(getapi24);
        }
        
        public hn.DataAccess.Model.SYS_SUBDICSMODEL[] GetDics_Area(string categorycode, string keyword, bool all) {
            return base.Channel.GetDics_Area(categorycode, keyword, all);
        }
        
        public hn.DataAccess.Model.v_thdModel getTHD(string thdbm) {
            return base.Channel.getTHD(thdbm);
        }
        
        public string ZFICPOBILL(string fEntryID) {
            return base.Channel.ZFICPOBILL(fEntryID);
        }
        
        public string ZFICPRBILLEntry(string fEntryID) {
            return base.Channel.ZFICPRBILLEntry(fEntryID);
        }
        
        public hn.DataAccess.Model.V_ICPOBILLMODEL getICPOBillCLientID(string thdbm) {
            return base.Channel.getICPOBillCLientID(thdbm);
        }
        
        public decimal getLeftNum_THD(string thdbm) {
            return base.Channel.getLeftNum_THD(thdbm);
        }
        
        public hn.DataAccess.model.V_PREMISEModel[] GetPremiseList(string keyword) {
            return base.Channel.GetPremiseList(keyword);
        }
        
        public hn.DataAccess.Model.TB_BrandModel[] GetBrandList(hn.Core.Model.User loginUser) {
            return base.Channel.GetBrandList(loginUser);
        }
        
        public hn.DataAccess.Model.V_CLIENTACCOUNTModel[] GetClientAccountList(string brandid, string keyword) {
            return base.Channel.GetClientAccountList(brandid, keyword);
        }
        
        public hn.DataAccess.Model.TB_EXPRESSCOMPANYModel[] GetExpressCompanyList(string keyword) {
            return base.Channel.GetExpressCompanyList(keyword);
        }
        
        public hn.DataAccess.model.ProductViewModel[] GetProductList(hn.Core.Model.User loginUser, string keyword) {
            return base.Channel.GetProductList(loginUser, keyword);
        }
        
        public hn.DataAccess.Model.SRCModel[] GetSrcList(string productid, string keyword) {
            return base.Channel.GetSrcList(productid, keyword);
        }
        
        public hn.DataAccess.model.TB_EBPLModel[] GetProvince() {
            return base.Channel.GetProvince();
        }
        
        public hn.DataAccess.model.TB_EBPLModel[] GetCity(string provinceid) {
            return base.Channel.GetCity(provinceid);
        }
        
        public hn.DataAccess.model.TB_EBPLModel[] GetDistrict(string cityid) {
            return base.Channel.GetDistrict(cityid);
        }
        
        public hn.DataAccess.model.ProductViewModel getProductView(string fid) {
            return base.Channel.getProductView(fid);
        }
        
        public hn.DataAccess.Model.SYS_SUBDICSMODEL GetSingleDics(string fid) {
            return base.Channel.GetSingleDics(fid);
        }
        
        public hn.DataAccess.model.TB_DELIVER_BASEModel[] GetDeliverBaseList(string brandid, string keyword) {
            return base.Channel.GetDeliverBaseList(brandid, keyword);
        }
        
        public hn.DataAccess.Model.V_CLIENTACCOUNTModel GetClientAccountSingle(string clientid) {
            return base.Channel.GetClientAccountSingle(clientid);
        }
        
        public hn.DataAccess.Model.V_CLIENTACCOUNTModel GetClientByAccount(string faccount) {
            return base.Channel.GetClientByAccount(faccount);
        }
        
        public hn.DataAccess.Model.V_ICPRBILLMODEL[] GetPurchasePlanList(hn.Core.Model.User loginUser, string classarea2name, string brand, int status, string premiseid, string billno, string startdate, string enddate, bool searchclose) {
            return base.Channel.GetPurchasePlanList(loginUser, classarea2name, brand, status, premiseid, billno, startdate, enddate, searchclose);
        }
        
        public hn.DataAccess.Model.V_ICPRBILLMODEL[] GetPurchasePlanImport(hn.Core.Model.User loginUser, string strQuery) {
            return base.Channel.GetPurchasePlanImport(loginUser, strQuery);
        }
        
        public hn.DataAccess.Model.V_ICPRBILLMODEL[] GetPurchasePlanImport2(hn.Core.Model.User loginUser, string strQuery, string brandid) {
            return base.Channel.GetPurchasePlanImport2(loginUser, strQuery, brandid);
        }
        
        public hn.DataAccess.Model.V_ICPRBILLMODEL[] GetPurchasePlanImport3(hn.Core.Model.User loginUser, hn.Common.Cls_query.P_QueryOrder pquery) {
            return base.Channel.GetPurchasePlanImport3(loginUser, pquery);
        }
        
        public hn.DataAccess.Model.V_ICPRBILLMODEL GetPurchasePlanModel(string icprbillid) {
            return base.Channel.GetPurchasePlanModel(icprbillid);
        }
        
        public hn.DataAccess.Model.V_ICPRBILLENTRYMODEL GetV_ICPRBILLENTRYMODEL(string FID) {
            return base.Channel.GetV_ICPRBILLENTRYMODEL(FID);
        }
        
        public hn.DataAccess.Model.V_ICPRBILLENTRYMODEL[] V_ICPRBILLENTRYMODEL_List(string fpremisename) {
            return base.Channel.V_ICPRBILLENTRYMODEL_List(fpremisename);
        }
        
        public hn.DataAccess.Model.V_ICPRBILLENTRYMODEL[] GetPurchasePlanEntryList(string icprbillid, string statu, bool bICPO) {
            return base.Channel.GetPurchasePlanEntryList(icprbillid, statu, bICPO);
        }
        
        public bool Delete_ICPO(string fid) {
            return base.Channel.Delete_ICPO(fid);
        }
        
        public hn.DataAccess.Model.V_ICPRBILLENTRYMODEL[] GetPurchasePlanEntryByDeliveryList(hn.Core.Model.User loginUser, string productinfo, string classarea2name, string premiseid, string brand, string deliveryaddr, string typename, string billno, int status, bool bHaveSL) {
            return base.Channel.GetPurchasePlanEntryByDeliveryList(loginUser, productinfo, classarea2name, premiseid, brand, deliveryaddr, typename, billno, status, bHaveSL);
        }
        
        public bool ConfirmSave(string action, hn.DataAccess.Model.ICPRBILLENTRYMODEL[] data, hn.Core.Model.User loginUser) {
            return base.Channel.ConfirmSave(action, data, loginUser);
        }
        
        public bool CloseSave(hn.DataAccess.Model.ICPRBILLENTRYMODEL[] data, hn.Core.Model.User loginUser, string content) {
            return base.Channel.CloseSave(data, loginUser, content);
        }
        
        public System.Data.DataTable GetStockList(string productname, string stockname, string productnumber, string wdr, string batchno, string brand, string mode, string colorno, bool isfactory, bool istrust) {
            return base.Channel.GetStockList(productname, stockname, productnumber, wdr, batchno, brand, mode, colorno, isfactory, istrust);
        }
        
        public MApiModel.recApi2.Rootobject GetStockListMN(MApiModel.api2.Rootobject getapi2) {
            return base.Channel.GetStockListMN(getapi2);
        }
        
        public MApiModel.recApi2.Rootobject GetStockListMN_2(MApiModel.api2.Rootobject getapi2, int comid) {
            return base.Channel.GetStockListMN_2(getapi2, comid);
        }
        
        public hn.DataAccess.Model.TB_ATTACHMENTModel[] GetAttachmentList(string icprbillid) {
            return base.Channel.GetAttachmentList(icprbillid);
        }
        
        public int UpdateICPRBILL(hn.DataAccess.Model.ICPRBILLMODEL model) {
            return base.Channel.UpdateICPRBILL(model);
        }
        
        public hn.DataAccess.Model.V_ICPRBILLENTRYMODEL[] RefrshPriceNumberList(string icprbillid, string[] entryids) {
            return base.Channel.RefrshPriceNumberList(icprbillid, entryids);
        }
        
        public hn.DataAccess.model.TB_PRICEPOLICYModel[] GetPriceNumberListByItemID(string itemid) {
            return base.Channel.GetPriceNumberListByItemID(itemid);
        }
        
        public hn.DataAccess.model.TB_PRICEPOLICYModel[] GetPriceNumberListByBrandID(string itemid) {
            return base.Channel.GetPriceNumberListByBrandID(itemid);
        }
        
        public void UpdateConfirmTime(string FPlanId) {
            base.Channel.UpdateConfirmTime(FPlanId);
        }
        
        public hn.DataAccess.Model.v_thdModel[] getTHDList(string[] thdbmList) {
            return base.Channel.getTHDList(thdbmList);
        }
        
        public string GetNewBillNo(string billtype) {
            return base.Channel.GetNewBillNo(billtype);
        }
        
        public bool DeleteGroupBill(string groupno) {
            return base.Channel.DeleteGroupBill(groupno);
        }
        
        public bool DeliveryBillSave(hn.DataAccess.Model.ICSEOUTBILLMODEL model, hn.DataAccess.Model.ICSEOUTBILLENTRYMODEL[] entrys, bool delivery) {
            return base.Channel.DeliveryBillSave(model, entrys, delivery);
        }
        
        public bool UpdateIdentification(string ids, string centent) {
            return base.Channel.UpdateIdentification(ids, centent);
        }
        
        public hn.DataAccess.Model.V_ICSEOUTBILLMODEL[] GetDeliveryList(
                    hn.Core.Model.User loginUser, 
                    string brand, 
                    string classarea2name, 
                    string premiseid, 
                    int status, 
                    string car, 
                    string stock, 
                    string account, 
                    string expresscompany, 
                    string factotryno, 
                    string billno, 
                    string groupno, 
                    string projectname, 
                    string startdate, 
                    string enddate, 
                    bool searchclose) {
            return base.Channel.GetDeliveryList(loginUser, brand, classarea2name, premiseid, status, car, stock, account, expresscompany, factotryno, billno, groupno, projectname, startdate, enddate, searchclose);
        }
        
        public hn.DataAccess.Model.V_ICSEOUTBILLENTRYMODEL[] GetDeliveryEntryList(string billid) {
            return base.Channel.GetDeliveryEntryList(billid);
        }
        
        public int DeleteDeliveryByIDs(string ids) {
            return base.Channel.DeleteDeliveryByIDs(ids);
        }
        
        public int AuditDeliveryByIDs(string ids, int status, hn.Core.Model.User loginUser) {
            return base.Channel.AuditDeliveryByIDs(ids, status, loginUser);
        }
        
        public int AuditAntiDeliveryByIDs(string ids) {
            return base.Channel.AuditAntiDeliveryByIDs(ids);
        }
        
        public string SyncDeliveryByIDs(string ids) {
            return base.Channel.SyncDeliveryByIDs(ids);
        }
        
        public string SyncDeliveryByIDsMN(string strJson, string fid) {
            return base.Channel.SyncDeliveryByIDsMN(strJson, fid);
        }
        
        public string SynDeliveryNot(string fid) {
            return base.Channel.SynDeliveryNot(fid);
        }
        
        public hn.DataAccess.Model.V_ICSEOUTBILLENTRYMODEL[] GetDeliveryEntryByGroupNo(string groupno) {
            return base.Channel.GetDeliveryEntryByGroupNo(groupno);
        }
        
        public hn.DataAccess.Model.V_ICSEOUTBILLMODEL[] GetDeliveryByGroupNo(string groupno) {
            return base.Channel.GetDeliveryByGroupNo(groupno);
        }
        
        public hn.DataAccess.Model.SRCModel GetSrcModelByItemID(string itemid) {
            return base.Channel.GetSrcModelByItemID(itemid);
        }
        
        public bool UpdateGetDeliveryEntryData(string id, decimal commitqty) {
            return base.Channel.UpdateGetDeliveryEntryData(id, commitqty);
        }
        
        public string GetDismantlingNo(string no) {
            return base.Channel.GetDismantlingNo(no);
        }
        
        public string UpdateDeliveryGroupStatus(string ids, int status) {
            return base.Channel.UpdateDeliveryGroupStatus(ids, status);
        }
        
        public string ContractCar(string[] ids) {
            return base.Channel.ContractCar(ids);
        }
        
        public string SaveICPOBILL(hn.DataAccess.Model.ICPOBILLMODEL ICPOBILL, hn.DataAccess.Model.ICPOBILLENTRYMODEL[] ICPOBILLENTRYList) {
            return base.Channel.SaveICPOBILL(ICPOBILL, ICPOBILLENTRYList);
        }
        
        public hn.DataAccess.Model.V_ICPOBILLMODEL[] GetOrderList(hn.Core.Model.User loginUser, string classarea2name, string brand, int status, string premiseid, string billno, string startdate, string enddate, bool searchclose) {
            return base.Channel.GetOrderList(loginUser, classarea2name, brand, status, premiseid, billno, startdate, enddate, searchclose);
        }
        
        public hn.DataAccess.Model.V_ICPOBILLENTRYMODEL[] GetOrderEntryList(string icprbillid, string status) {
            return base.Channel.GetOrderEntryList(icprbillid, status);
        }
        
        public hn.DataAccess.Model.ICPOBILLMODEL GetSingleOrder(string icprbillid) {
            return base.Channel.GetSingleOrder(icprbillid);
        }
        
        public hn.DataAccess.Model.ICPO_BOLentryModel[] GeICPO_BOLList(hn.Core.Model.User loginUser, string FPObillno, string Ficbolno, int FSYNCSTATUS, string FACCOUNT, string FITEMID, string startdate, string enddate, bool searchclose) {
            return base.Channel.GeICPO_BOLList(loginUser, FPObillno, Ficbolno, FSYNCSTATUS, FACCOUNT, FITEMID, startdate, enddate, searchclose);
        }
        
        public string GetStartDate_syn() {
            return base.Channel.GetStartDate_syn();
        }
        
        public string GetStartDate_syn_cc() {
            return base.Channel.GetStartDate_syn_cc();
        }
        
        public hn.DataAccess.model.TB_PREMISEModel[] GetJYDW(string keyword) {
            return base.Channel.GetJYDW(keyword);
        }
        
        public hn.DataAccess.Model.SRCModel getSrc(string pz, string gg, string xh) {
            return base.Channel.getSrc(pz, gg, xh);
        }
        
        public hn.DataAccess.Model.SYS_SUBDICSMODEL GetArea2(string fid) {
            return base.Channel.GetArea2(fid);
        }
        
        public string GeICPO_BOLListMN_syn(System.DateTime starttime) {
            return base.Channel.GeICPO_BOLListMN_syn(starttime);
        }
        
        public int GetLocalSum(string autoid, string icseoutbillentryid) {
            return base.Channel.GetLocalSum(autoid, icseoutbillentryid);
        }
        
        public string GeICPO_BOLListMN_syn_cc(System.DateTime starttime) {
            return base.Channel.GeICPO_BOLListMN_syn_cc(starttime);
        }
        
        public string GetCCD(System.DateTime starttime) {
            return base.Channel.GetCCD(starttime);
        }
        
        public hn.DataAccess.model.v_thd[] v_thdModel_List() {
            return base.Channel.v_thdModel_List();
        }
        
        public string[] v_thdModelName_List() {
            return base.Channel.v_thdModelName_List();
        }
        
        public hn.DataAccess.Model.v_thdModel[] GeICPO_BOLListMN_db(MApiModel.api8.Rootobject getapi8, string cpxh, string cpgg, string jhdh, string thd, string area2, int bNotArea) {
            return base.Channel.GeICPO_BOLListMN_db(getapi8, cpxh, cpgg, jhdh, thd, area2, bNotArea);
        }
        
        public bool ConfirmSave_ICPO(string action, hn.DataAccess.Model.ICPOBILLENTRYMODEL[] data, hn.Core.Model.User loginUser) {
            return base.Channel.ConfirmSave_ICPO(action, data, loginUser);
        }
        
        public bool CloseSave_ICPO(hn.DataAccess.Model.ICPOBILLENTRYMODEL[] data, hn.Core.Model.User loginUser, string content) {
            return base.Channel.CloseSave_ICPO(data, loginUser, content);
        }
        
        public bool AuditSave_ICPO(hn.DataAccess.Model.ICPOBILLENTRYMODEL[] data, hn.Core.Model.User loginUser, string content) {
            return base.Channel.AuditSave_ICPO(data, loginUser, content);
        }
    }
}
