//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hn.Client.Service.FactoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICPOBILLENTRYModel_MHLS", Namespace="http://schemas.datacontract.org/2004/07/hn.APIService.DataAccess.Model")]
    [System.SerializableAttribute()]
    public partial class ICPOBILLENTRYModel_MHLS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FACCOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FAUDQTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FBILLNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FCOLORNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FDesBillNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FENTRYIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FERR_MESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FITEMIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FPOtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FREMARKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSRCCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSRCMODELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSRCNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FSTATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FSYNCSTATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTIMESTAMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FamountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FcompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FcontractNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FdesbillentryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FentryTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FnoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FpricepolicyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FprojectNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FstockNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal fpriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FACCOUNT {
            get {
                return this.FACCOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.FACCOUNTField, value) != true)) {
                    this.FACCOUNTField = value;
                    this.RaisePropertyChanged("FACCOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FAUDQTY {
            get {
                return this.FAUDQTYField;
            }
            set {
                if ((this.FAUDQTYField.Equals(value) != true)) {
                    this.FAUDQTYField = value;
                    this.RaisePropertyChanged("FAUDQTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FBILLNO {
            get {
                return this.FBILLNOField;
            }
            set {
                if ((object.ReferenceEquals(this.FBILLNOField, value) != true)) {
                    this.FBILLNOField = value;
                    this.RaisePropertyChanged("FBILLNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FCOLORNO {
            get {
                return this.FCOLORNOField;
            }
            set {
                if ((object.ReferenceEquals(this.FCOLORNOField, value) != true)) {
                    this.FCOLORNOField = value;
                    this.RaisePropertyChanged("FCOLORNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FDesBillNo {
            get {
                return this.FDesBillNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FDesBillNoField, value) != true)) {
                    this.FDesBillNoField = value;
                    this.RaisePropertyChanged("FDesBillNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FENTRYID {
            get {
                return this.FENTRYIDField;
            }
            set {
                if ((this.FENTRYIDField.Equals(value) != true)) {
                    this.FENTRYIDField = value;
                    this.RaisePropertyChanged("FENTRYID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FERR_MESSAGE {
            get {
                return this.FERR_MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.FERR_MESSAGEField, value) != true)) {
                    this.FERR_MESSAGEField = value;
                    this.RaisePropertyChanged("FERR_MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FID {
            get {
                return this.FIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FIDField, value) != true)) {
                    this.FIDField = value;
                    this.RaisePropertyChanged("FID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FITEMID {
            get {
                return this.FITEMIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FITEMIDField, value) != true)) {
                    this.FITEMIDField = value;
                    this.RaisePropertyChanged("FITEMID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FPOtype {
            get {
                return this.FPOtypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FPOtypeField, value) != true)) {
                    this.FPOtypeField = value;
                    this.RaisePropertyChanged("FPOtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FREMARK {
            get {
                return this.FREMARKField;
            }
            set {
                if ((object.ReferenceEquals(this.FREMARKField, value) != true)) {
                    this.FREMARKField = value;
                    this.RaisePropertyChanged("FREMARK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSRCCODE {
            get {
                return this.FSRCCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.FSRCCODEField, value) != true)) {
                    this.FSRCCODEField = value;
                    this.RaisePropertyChanged("FSRCCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSRCMODEL {
            get {
                return this.FSRCMODELField;
            }
            set {
                if ((object.ReferenceEquals(this.FSRCMODELField, value) != true)) {
                    this.FSRCMODELField = value;
                    this.RaisePropertyChanged("FSRCMODEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSRCNAME {
            get {
                return this.FSRCNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FSRCNAMEField, value) != true)) {
                    this.FSRCNAMEField = value;
                    this.RaisePropertyChanged("FSRCNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FSTATUS {
            get {
                return this.FSTATUSField;
            }
            set {
                if ((this.FSTATUSField.Equals(value) != true)) {
                    this.FSTATUSField = value;
                    this.RaisePropertyChanged("FSTATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FSYNCSTATUS {
            get {
                return this.FSYNCSTATUSField;
            }
            set {
                if ((this.FSYNCSTATUSField.Equals(value) != true)) {
                    this.FSYNCSTATUSField = value;
                    this.RaisePropertyChanged("FSYNCSTATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FTIMESTAMP {
            get {
                return this.FTIMESTAMPField;
            }
            set {
                if ((object.ReferenceEquals(this.FTIMESTAMPField, value) != true)) {
                    this.FTIMESTAMPField = value;
                    this.RaisePropertyChanged("FTIMESTAMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Famount {
            get {
                return this.FamountField;
            }
            set {
                if ((this.FamountField.Equals(value) != true)) {
                    this.FamountField = value;
                    this.RaisePropertyChanged("Famount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fcompany {
            get {
                return this.FcompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.FcompanyField, value) != true)) {
                    this.FcompanyField = value;
                    this.RaisePropertyChanged("Fcompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FcontractNO {
            get {
                return this.FcontractNOField;
            }
            set {
                if ((object.ReferenceEquals(this.FcontractNOField, value) != true)) {
                    this.FcontractNOField = value;
                    this.RaisePropertyChanged("FcontractNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fdesbillentry {
            get {
                return this.FdesbillentryField;
            }
            set {
                if ((this.FdesbillentryField.Equals(value) != true)) {
                    this.FdesbillentryField = value;
                    this.RaisePropertyChanged("Fdesbillentry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FentryTotal {
            get {
                return this.FentryTotalField;
            }
            set {
                if ((this.FentryTotalField.Equals(value) != true)) {
                    this.FentryTotalField = value;
                    this.RaisePropertyChanged("FentryTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flevel {
            get {
                return this.FlevelField;
            }
            set {
                if ((object.ReferenceEquals(this.FlevelField, value) != true)) {
                    this.FlevelField = value;
                    this.RaisePropertyChanged("Flevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fnote {
            get {
                return this.FnoteField;
            }
            set {
                if ((object.ReferenceEquals(this.FnoteField, value) != true)) {
                    this.FnoteField = value;
                    this.RaisePropertyChanged("Fnote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fpricepolicy {
            get {
                return this.FpricepolicyField;
            }
            set {
                if ((object.ReferenceEquals(this.FpricepolicyField, value) != true)) {
                    this.FpricepolicyField = value;
                    this.RaisePropertyChanged("Fpricepolicy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FprojectNO {
            get {
                return this.FprojectNOField;
            }
            set {
                if ((object.ReferenceEquals(this.FprojectNOField, value) != true)) {
                    this.FprojectNOField = value;
                    this.RaisePropertyChanged("FprojectNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FstockNO {
            get {
                return this.FstockNOField;
            }
            set {
                if ((object.ReferenceEquals(this.FstockNOField, value) != true)) {
                    this.FstockNOField = value;
                    this.RaisePropertyChanged("FstockNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Funit {
            get {
                return this.FunitField;
            }
            set {
                if ((object.ReferenceEquals(this.FunitField, value) != true)) {
                    this.FunitField = value;
                    this.RaisePropertyChanged("Funit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal fprice {
            get {
                return this.fpriceField;
            }
            set {
                if ((this.fpriceField.Equals(value) != true)) {
                    this.fpriceField = value;
                    this.RaisePropertyChanged("fprice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICPO_BOLentryModel_MNLS", Namespace="http://schemas.datacontract.org/2004/07/hn.APIService.DataAccess.Model")]
    [System.SerializableAttribute()]
    public partial class ICPO_BOLentryModel_MNLS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FACCOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FAUDQTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FCOLORNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FITEMIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FPObillnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FREMARKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FSRCCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FSRCMODELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FSRCNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FSYNCSTATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FTIMESTAMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FamountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FcommitQTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FcontractNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FicbolentryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FicbolnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FpobillentryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FprojectNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FstockNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FunitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fpriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FACCOUNT {
            get {
                return this.FACCOUNTField;
            }
            set {
                if ((this.FACCOUNTField.Equals(value) != true)) {
                    this.FACCOUNTField = value;
                    this.RaisePropertyChanged("FACCOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FAUDQTY {
            get {
                return this.FAUDQTYField;
            }
            set {
                if ((this.FAUDQTYField.Equals(value) != true)) {
                    this.FAUDQTYField = value;
                    this.RaisePropertyChanged("FAUDQTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FCOLORNO {
            get {
                return this.FCOLORNOField;
            }
            set {
                if ((this.FCOLORNOField.Equals(value) != true)) {
                    this.FCOLORNOField = value;
                    this.RaisePropertyChanged("FCOLORNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FDATE {
            get {
                return this.FDATEField;
            }
            set {
                if ((this.FDATEField.Equals(value) != true)) {
                    this.FDATEField = value;
                    this.RaisePropertyChanged("FDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FID {
            get {
                return this.FIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FIDField, value) != true)) {
                    this.FIDField = value;
                    this.RaisePropertyChanged("FID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FITEMID {
            get {
                return this.FITEMIDField;
            }
            set {
                if ((this.FITEMIDField.Equals(value) != true)) {
                    this.FITEMIDField = value;
                    this.RaisePropertyChanged("FITEMID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FPObillno {
            get {
                return this.FPObillnoField;
            }
            set {
                if ((object.ReferenceEquals(this.FPObillnoField, value) != true)) {
                    this.FPObillnoField = value;
                    this.RaisePropertyChanged("FPObillno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FREMARK {
            get {
                return this.FREMARKField;
            }
            set {
                if ((this.FREMARKField.Equals(value) != true)) {
                    this.FREMARKField = value;
                    this.RaisePropertyChanged("FREMARK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FSRCCODE {
            get {
                return this.FSRCCODEField;
            }
            set {
                if ((this.FSRCCODEField.Equals(value) != true)) {
                    this.FSRCCODEField = value;
                    this.RaisePropertyChanged("FSRCCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FSRCMODEL {
            get {
                return this.FSRCMODELField;
            }
            set {
                if ((this.FSRCMODELField.Equals(value) != true)) {
                    this.FSRCMODELField = value;
                    this.RaisePropertyChanged("FSRCMODEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FSRCNAME {
            get {
                return this.FSRCNAMEField;
            }
            set {
                if ((this.FSRCNAMEField.Equals(value) != true)) {
                    this.FSRCNAMEField = value;
                    this.RaisePropertyChanged("FSRCNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FSYNCSTATUS {
            get {
                return this.FSYNCSTATUSField;
            }
            set {
                if ((this.FSYNCSTATUSField.Equals(value) != true)) {
                    this.FSYNCSTATUSField = value;
                    this.RaisePropertyChanged("FSYNCSTATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FTIMESTAMP {
            get {
                return this.FTIMESTAMPField;
            }
            set {
                if ((this.FTIMESTAMPField.Equals(value) != true)) {
                    this.FTIMESTAMPField = value;
                    this.RaisePropertyChanged("FTIMESTAMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Famount {
            get {
                return this.FamountField;
            }
            set {
                if ((this.FamountField.Equals(value) != true)) {
                    this.FamountField = value;
                    this.RaisePropertyChanged("Famount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FcommitQTY {
            get {
                return this.FcommitQTYField;
            }
            set {
                if ((this.FcommitQTYField.Equals(value) != true)) {
                    this.FcommitQTYField = value;
                    this.RaisePropertyChanged("FcommitQTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FcontractNO {
            get {
                return this.FcontractNOField;
            }
            set {
                if ((this.FcontractNOField.Equals(value) != true)) {
                    this.FcontractNOField = value;
                    this.RaisePropertyChanged("FcontractNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ficbolentry {
            get {
                return this.FicbolentryField;
            }
            set {
                if ((this.FicbolentryField.Equals(value) != true)) {
                    this.FicbolentryField = value;
                    this.RaisePropertyChanged("Ficbolentry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ficbolno {
            get {
                return this.FicbolnoField;
            }
            set {
                if ((object.ReferenceEquals(this.FicbolnoField, value) != true)) {
                    this.FicbolnoField = value;
                    this.RaisePropertyChanged("Ficbolno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Flevel {
            get {
                return this.FlevelField;
            }
            set {
                if ((this.FlevelField.Equals(value) != true)) {
                    this.FlevelField = value;
                    this.RaisePropertyChanged("Flevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fpobillentry {
            get {
                return this.FpobillentryField;
            }
            set {
                if ((object.ReferenceEquals(this.FpobillentryField, value) != true)) {
                    this.FpobillentryField = value;
                    this.RaisePropertyChanged("Fpobillentry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FprojectNO {
            get {
                return this.FprojectNOField;
            }
            set {
                if ((object.ReferenceEquals(this.FprojectNOField, value) != true)) {
                    this.FprojectNOField = value;
                    this.RaisePropertyChanged("FprojectNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FstockNO {
            get {
                return this.FstockNOField;
            }
            set {
                if ((this.FstockNOField.Equals(value) != true)) {
                    this.FstockNOField = value;
                    this.RaisePropertyChanged("FstockNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Funit {
            get {
                return this.FunitField;
            }
            set {
                if ((this.FunitField.Equals(value) != true)) {
                    this.FunitField = value;
                    this.RaisePropertyChanged("Funit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fprice {
            get {
                return this.fpriceField;
            }
            set {
                if ((this.fpriceField.Equals(value) != true)) {
                    this.fpriceField = value;
                    this.RaisePropertyChanged("fprice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FactoryService.IAPIService")]
    public interface IAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/WmStock", ReplyAction="http://tempuri.org/IAPIService/WmStockResponse")]
        System.Data.DataTable WmStock(out int pagecount, string productnumber, string productname, string stockname, string brandname, string batchno, string wdr, string mode, string colorno, int pagesize, int page, bool isfactory, bool istrust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/ICSEOUTBILLSync", ReplyAction="http://tempuri.org/IAPIService/ICSEOUTBILLSyncResponse")]
        string ICSEOUTBILLSync(hn.DataAccess.Model.V_ICSEOUTBILLMODEL[] icseout, hn.DataAccess.Model.V_ICSEOUTBILLENTRYMODEL[] icseoutentry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetICSEOUTUpdateData", ReplyAction="http://tempuri.org/IAPIService/GetICSEOUTUpdateDataResponse")]
        System.Data.DataTable GetICSEOUTUpdateData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateCSEOUTSyncStatus", ReplyAction="http://tempuri.org/IAPIService/UpdateCSEOUTSyncStatusResponse")]
        string UpdateCSEOUTSyncStatus(int id, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetICSEOUTUpdateData2", ReplyAction="http://tempuri.org/IAPIService/GetICSEOUTUpdateData2Response")]
        System.Data.DataTable GetICSEOUTUpdateData2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateCSEOUTSyncStatus2", ReplyAction="http://tempuri.org/IAPIService/UpdateCSEOUTSyncStatus2Response")]
        string UpdateCSEOUTSyncStatus2(int id, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetSTOCKUpdateData", ReplyAction="http://tempuri.org/IAPIService/GetSTOCKUpdateDataResponse")]
        System.Data.DataTable GetSTOCKUpdateData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetTMP_STOCKBill", ReplyAction="http://tempuri.org/IAPIService/GetTMP_STOCKBillResponse")]
        System.Data.DataTable GetTMP_STOCKBill();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateTMP_STOCKBillStatus", ReplyAction="http://tempuri.org/IAPIService/UpdateTMP_STOCKBillStatusResponse")]
        string UpdateTMP_STOCKBillStatus(int id, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetFinfo_RE_id0", ReplyAction="http://tempuri.org/IAPIService/GetFinfo_RE_id0Response")]
        System.Data.DataTable GetFinfo_RE_id0();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/UpdateFinfo_RE_id", ReplyAction="http://tempuri.org/IAPIService/UpdateFinfo_RE_idResponse")]
        string UpdateFinfo_RE_id(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/InventorySync", ReplyAction="http://tempuri.org/IAPIService/InventorySyncResponse")]
        string InventorySync(hn.DataAccess.Model.SALES_ORDER_DATAMODEL[] salesOrderDatas, hn.DataAccess.Model.SALESOUT_DATAMODEL[] salesoutDatas, hn.DataAccess.Model.TP_INVENTORYMODEL[] inventorys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/InsertICPOEntry", ReplyAction="http://tempuri.org/IAPIService/InsertICPOEntryResponse")]
        bool InsertICPOEntry(string strModelJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetICPOEntry", ReplyAction="http://tempuri.org/IAPIService/GetICPOEntryResponse")]
        hn.Client.Service.FactoryService.ICPOBILLENTRYModel_MHLS GetICPOEntry(string strFID, string strEntryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetICPO_BOEntry", ReplyAction="http://tempuri.org/IAPIService/GetICPO_BOEntryResponse")]
        hn.Client.Service.FactoryService.ICPO_BOLentryModel_MNLS[] GetICPO_BOEntry(string fbillno, string entryid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/SetICPO_BOEntryStatus", ReplyAction="http://tempuri.org/IAPIService/SetICPO_BOEntryStatusResponse")]
        int SetICPO_BOEntryStatus(string fbillno, string entryid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAPIServiceChannel : hn.Client.Service.FactoryService.IAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIServiceClient : System.ServiceModel.ClientBase<hn.Client.Service.FactoryService.IAPIService>, hn.Client.Service.FactoryService.IAPIService {
        
        public APIServiceClient() {
        }
        
        public APIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable WmStock(out int pagecount, string productnumber, string productname, string stockname, string brandname, string batchno, string wdr, string mode, string colorno, int pagesize, int page, bool isfactory, bool istrust) {
            return base.Channel.WmStock(out pagecount, productnumber, productname, stockname, brandname, batchno, wdr, mode, colorno, pagesize, page, isfactory, istrust);
        }
        
        public string ICSEOUTBILLSync(hn.DataAccess.Model.V_ICSEOUTBILLMODEL[] icseout, hn.DataAccess.Model.V_ICSEOUTBILLENTRYMODEL[] icseoutentry) {
            return base.Channel.ICSEOUTBILLSync(icseout, icseoutentry);
        }
        
        public System.Data.DataTable GetICSEOUTUpdateData() {
            return base.Channel.GetICSEOUTUpdateData();
        }
        
        public string UpdateCSEOUTSyncStatus(int id, int status) {
            return base.Channel.UpdateCSEOUTSyncStatus(id, status);
        }
        
        public System.Data.DataTable GetICSEOUTUpdateData2() {
            return base.Channel.GetICSEOUTUpdateData2();
        }
        
        public string UpdateCSEOUTSyncStatus2(int id, int status) {
            return base.Channel.UpdateCSEOUTSyncStatus2(id, status);
        }
        
        public System.Data.DataTable GetSTOCKUpdateData() {
            return base.Channel.GetSTOCKUpdateData();
        }
        
        public System.Data.DataTable GetTMP_STOCKBill() {
            return base.Channel.GetTMP_STOCKBill();
        }
        
        public string UpdateTMP_STOCKBillStatus(int id, int status) {
            return base.Channel.UpdateTMP_STOCKBillStatus(id, status);
        }
        
        public System.Data.DataTable GetFinfo_RE_id0() {
            return base.Channel.GetFinfo_RE_id0();
        }
        
        public string UpdateFinfo_RE_id(int id) {
            return base.Channel.UpdateFinfo_RE_id(id);
        }
        
        public string InventorySync(hn.DataAccess.Model.SALES_ORDER_DATAMODEL[] salesOrderDatas, hn.DataAccess.Model.SALESOUT_DATAMODEL[] salesoutDatas, hn.DataAccess.Model.TP_INVENTORYMODEL[] inventorys) {
            return base.Channel.InventorySync(salesOrderDatas, salesoutDatas, inventorys);
        }
        
        public bool InsertICPOEntry(string strModelJson) {
            return base.Channel.InsertICPOEntry(strModelJson);
        }
        
        public hn.Client.Service.FactoryService.ICPOBILLENTRYModel_MHLS GetICPOEntry(string strFID, string strEntryID) {
            return base.Channel.GetICPOEntry(strFID, strEntryID);
        }
        
        public hn.Client.Service.FactoryService.ICPO_BOLentryModel_MNLS[] GetICPO_BOEntry(string fbillno, string entryid) {
            return base.Channel.GetICPO_BOEntry(fbillno, entryid);
        }
        
        public int SetICPO_BOEntryStatus(string fbillno, string entryid) {
            return base.Channel.SetICPO_BOEntryStatus(fbillno, entryid);
        }
    }
}
